// Integration tests for Phase 1.3 (payments table + status derivation)
// and Phase 1.2 (accounting auto-post with reversal on void).

const test = require('node:test');
const assert = require('node:assert/strict');
const { useTempDataDir, request } = require('./helpers');

const tmp = useTempDataDir();
const app = require('../index');

let server;
let token;

test.before(async () => {
  server = app.listen(0);
  await new Promise(r => server.on('listening', r));
  const res = await request(server, 'POST', '/api/admin/login', {
    body: { email: 'jmanharth@gmail.com', password: 'Password26!' },
  });
  token = res.body.token;
});

test.after(() => {
  if (server) server.close();
  tmp.cleanup();
});

// Helper: create a job and mark it completed so we get a draft invoice
// auto-generated by Phase 1.1, then stamp a price on it so it has a balance.
async function makeInvoiceWithBalance(amount = 250, customerName = 'Payments Tester') {
  // Create a job
  const jobRes = await request(server, 'POST', '/api/admin/jobs', {
    token,
    body: { customerName, serviceType: 'Termite Treatment' },
  });
  const jobId = jobRes.body.job.id;

  // Mark it completed to trigger auto-draft
  const patchRes = await request(server, 'PATCH', `/api/admin/jobs/${jobId}`, {
    token,
    body: { status: 'completed' },
  });
  const draft = patchRes.body.autoInvoice;
  assert.ok(draft, 'auto-draft should have fired');

  // Manually re-POST an invoice with the same jobId? No — simpler: the
  // draft is fine, but has $0 line item. Delete it and create a new one
  // with a real price so the balance > 0.
  // Actually even simpler: just verify our payment logic against the
  // zero-balance draft separately, and for paid-state tests create a
  // fresh invoice directly via POST /api/admin/invoices.
  // Here we POST a fresh invoice with a real rate.
  const fresh = await request(server, 'POST', '/api/admin/invoices', {
    token,
    body: {
      customerName,
      customerEmail: 'pay@example.com',
      items: [{ description: 'Termite Treatment', quantity: 1, rate: amount }],
    },
  });
  assert.equal(fresh.status, 200);
  return fresh.body.invoice;
}

async function getInvoice(id) {
  const res = await request(server, 'GET', '/api/admin/invoices', { token });
  return (res.body.invoices || []).find(i => i.id === id);
}

test('payment endpoints exist and reject invalid inputs', async () => {
  const inv = await makeInvoiceWithBalance();

  const missingAmount = await request(server, 'POST', `/api/admin/invoices/${inv.id}/payments`, {
    token,
    body: {},
  });
  assert.equal(missingAmount.status, 400);
  assert.ok(/amount/i.test(missingAmount.body.error));

  const zero = await request(server, 'POST', `/api/admin/invoices/${inv.id}/payments`, {
    token,
    body: { amount: 0, paymentMethod: 'cash' },
  });
  assert.equal(zero.status, 400);

  const badMethod = await request(server, 'POST', `/api/admin/invoices/${inv.id}/payments`, {
    token,
    body: { amount: 50, paymentMethod: 'crypto' },
  });
  assert.equal(badMethod.status, 400);
  assert.ok(/paymentMethod/.test(badMethod.body.error));

  const notFound = await request(server, 'POST', '/api/admin/invoices/nonexistent/payments', {
    token,
    body: { amount: 50 },
  });
  assert.equal(notFound.status, 404);
});

test('recording a full-balance payment marks invoice as paid', async () => {
  const inv = await makeInvoiceWithBalance(100);
  const totalWithTax = inv.total; // 100 + 8.5% tax = 108.50

  const pay = await request(server, 'POST', `/api/admin/invoices/${inv.id}/payments`, {
    token,
    body: { amount: totalWithTax, paymentMethod: 'cash', referenceNumber: 'CHK-001' },
  });
  assert.equal(pay.status, 200);
  assert.ok(pay.body.payment.id);
  assert.equal(pay.body.invoice.effectiveStatus, 'paid');
  assert.equal(pay.body.invoice.paidAmount, totalWithTax);
  assert.equal(pay.body.invoice.balance, 0);
  assert.equal(pay.body.invoice.payments.length, 1);
  assert.equal(pay.body.invoice.payments[0].referenceNumber, 'CHK-001');
});

test('partial payment marks invoice as partial and tracks balance', async () => {
  const inv = await makeInvoiceWithBalance(200);
  const half = Math.round((inv.total / 2) * 100) / 100;

  const pay = await request(server, 'POST', `/api/admin/invoices/${inv.id}/payments`, {
    token,
    body: { amount: half, paymentMethod: 'check' },
  });
  assert.equal(pay.status, 200);
  assert.equal(pay.body.invoice.effectiveStatus, 'partial');
  assert.equal(pay.body.invoice.paidAmount, half);
  assert.ok(Math.abs(pay.body.invoice.balance - (inv.total - half)) < 0.01);

  // A second partial that completes the balance should flip to 'paid'
  const pay2 = await request(server, 'POST', `/api/admin/invoices/${inv.id}/payments`, {
    token,
    body: { amount: inv.total - half, paymentMethod: 'card' },
  });
  assert.equal(pay2.status, 200);
  assert.equal(pay2.body.invoice.effectiveStatus, 'paid');
  assert.equal(pay2.body.invoice.balance, 0);
  assert.equal(pay2.body.invoice.payments.length, 2);
});

test('payment amount exceeding remaining balance is rejected', async () => {
  const inv = await makeInvoiceWithBalance(50);

  const overpay = await request(server, 'POST', `/api/admin/invoices/${inv.id}/payments`, {
    token,
    body: { amount: inv.total + 100, paymentMethod: 'cash' },
  });
  assert.equal(overpay.status, 400);
  assert.ok(/exceeds remaining balance/i.test(overpay.body.error));
});

test('payment auto-posts to transactions feed AND accounting ledger', async () => {
  const inv = await makeInvoiceWithBalance(150);

  // Snapshot before
  const txnsBefore = (await request(server, 'GET', '/api/admin/transactions', { token })).body.transactions;
  const jeBefore = (await request(server, 'GET', '/api/accounting/journal-entries', { token })).body.data || [];

  await request(server, 'POST', `/api/admin/invoices/${inv.id}/payments`, {
    token,
    body: { amount: inv.total, paymentMethod: 'cash' },
  });

  const txnsAfter = (await request(server, 'GET', '/api/admin/transactions', { token })).body.transactions;
  const jeAfter = (await request(server, 'GET', '/api/accounting/journal-entries', { token })).body.data || [];

  // One new income transaction
  const newTxns = txnsAfter.filter(t => !txnsBefore.some(b => b.id === t.id));
  assert.equal(newTxns.length, 1);
  assert.equal(newTxns[0].type, 'income');
  assert.equal(newTxns[0].amount, inv.total);

  // At least one new journal entry (the revenue entry: Dr Cash / Cr Revenue)
  const newJE = jeAfter.filter(e => !jeBefore.some(b => b.id === e.id));
  assert.ok(newJE.length >= 1, 'expected a journal entry for the payment');
  // Entry must balance
  const ent = newJE[0];
  const debits = ent.lines.reduce((s, l) => s + Number(l.debit), 0);
  const credits = ent.lines.reduce((s, l) => s + Number(l.credit), 0);
  assert.ok(Math.abs(debits - credits) < 0.01);
  assert.ok(Math.abs(debits - inv.total) < 0.01);
});

test('DELETE /api/admin/payments/:id reverses BOTH the transaction and the journal entry (no silent orphaning)', async () => {
  const inv = await makeInvoiceWithBalance(180);

  const payRes = await request(server, 'POST', `/api/admin/invoices/${inv.id}/payments`, {
    token,
    body: { amount: inv.total, paymentMethod: 'cash' },
  });
  const paymentId = payRes.body.payment.id;
  const journalEntryId = payRes.body.payment.journalEntryId;
  assert.ok(journalEntryId, 'payment should have been linked to a journal entry');

  // Snapshot after the payment was recorded
  const incomeBefore = (await request(server, 'GET', '/api/admin/transactions', { token }))
    .body.transactions
    .filter(t => t.type === 'income' && !t.reversalOf)
    .reduce((s, t) => s + Number(t.amount), 0);

  // Void the payment
  const del = await request(server, 'DELETE', `/api/admin/payments/${paymentId}`, { token });
  assert.equal(del.status, 200);
  assert.equal(del.body.invoice.effectiveStatus, 'draft', 'invoice with no payments should be back to draft');
  assert.equal(del.body.invoice.paidAmount, 0);
  assert.equal(del.body.invoice.balance, inv.total);

  // The reversal transaction is a NEW row with negative amount — original
  // is still present (audit integrity), but net sum is zero.
  const txnsAfter = (await request(server, 'GET', '/api/admin/transactions', { token })).body.transactions;
  const reversal = txnsAfter.find(t => t.reversalOf && /REVERSAL/.test(t.description || ''));
  assert.ok(reversal, 'a reversal transaction should have been added');
  assert.ok(reversal.amount < 0, 'reversal amount must be negative');
  assert.equal(-reversal.amount, inv.total);

  // The journal entry was voided AND a reversing entry exists in accounting.
  const jeRes = await request(server, 'GET', '/api/accounting/journal-entries', { token });
  const entries = jeRes.body.data || [];
  const original = entries.find(e => e.id === journalEntryId);
  assert.ok(original, 'original entry still present (not deleted)');
  assert.equal(original.isVoid, true, 'original entry should be marked isVoid=true');
  const reversingEntry = entries.find(e => e.sourceType === 'reversal' && e.sourceId === journalEntryId);
  assert.ok(reversingEntry, 'a reversing journal entry should exist');
  // Reversing entry must balance (and flip debits/credits of the original)
  const d = reversingEntry.lines.reduce((s, l) => s + Number(l.debit), 0);
  const c = reversingEntry.lines.reduce((s, l) => s + Number(l.credit), 0);
  assert.ok(Math.abs(d - c) < 0.01);
});

test('legacy PATCH status=paid self-heals: auto-creates a payment for the balance', async () => {
  const inv = await makeInvoiceWithBalance(75);

  // Old client still sends PATCH status=paid — should not be rejected,
  // should instead auto-record a payment for the full balance.
  const patchRes = await request(server, 'PATCH', `/api/admin/invoices/${inv.id}`, {
    token,
    body: { status: 'paid' },
  });
  assert.equal(patchRes.status, 200);
  assert.ok(patchRes.body.synthesizedPayment, 'legacy PATCH should synthesize a payment');
  assert.equal(patchRes.body.invoice.effectiveStatus, 'paid');
  assert.equal(patchRes.body.invoice.balance, 0);
});

test('PATCH rejects unsupported status values', async () => {
  const inv = await makeInvoiceWithBalance(60);

  // 'partial' is a derived status — not manually settable
  const bad = await request(server, 'PATCH', `/api/admin/invoices/${inv.id}`, {
    token,
    body: { status: 'partial' },
  });
  assert.equal(bad.status, 400);
  assert.ok(/not manually settable/i.test(bad.body.error));
});

test('PATCH still accepts draft and sent status transitions', async () => {
  const inv = await makeInvoiceWithBalance(40);

  const sent = await request(server, 'PATCH', `/api/admin/invoices/${inv.id}`, {
    token,
    body: { status: 'sent' },
  });
  assert.equal(sent.status, 200);
  assert.equal(sent.body.invoice.baseStatus, 'sent');
  assert.equal(sent.body.invoice.effectiveStatus, 'sent'); // not overdue, not paid

  const draft = await request(server, 'PATCH', `/api/admin/invoices/${inv.id}`, {
    token,
    body: { status: 'draft' },
  });
  assert.equal(draft.status, 200);
  assert.equal(draft.body.invoice.baseStatus, 'draft');
});

test('overdue is derived from past due date on a sent invoice', async () => {
  const inv = await makeInvoiceWithBalance(90);

  // Mark sent and set a due date in the past
  await request(server, 'PATCH', `/api/admin/invoices/${inv.id}`, {
    token,
    body: { status: 'sent' },
  });
  // Directly edit the stored dueDate via the generic PATCH notes... actually
  // the current PATCH handler only accepts notes and status — dueDate can't
  // be PATCHed. Instead we just verify the derivation logic: if dueDate is
  // past and payments < total, effectiveStatus is 'overdue'.
  // Hack: read the invoice, backdate its dueDate via a fresh POST.
  // Simpler: create another invoice with a past due date.
  const past = new Date();
  past.setDate(past.getDate() - 10);
  const pastDue = past.toISOString().slice(0, 10);

  const create = await request(server, 'POST', '/api/admin/invoices', {
    token,
    body: {
      customerName: 'Overdue Tester',
      items: [{ description: 'Service', quantity: 1, rate: 100 }],
      dueDate: pastDue,
    },
  });
  await request(server, 'PATCH', `/api/admin/invoices/${create.body.invoice.id}`, {
    token,
    body: { status: 'sent' },
  });
  const fetched = await getInvoice(create.body.invoice.id);
  assert.equal(fetched.effectiveStatus, 'overdue');
});

test('GET /api/admin/invoices/:id/payments returns the payment history', async () => {
  const inv = await makeInvoiceWithBalance(200);
  await request(server, 'POST', `/api/admin/invoices/${inv.id}/payments`, {
    token,
    body: { amount: 50, paymentMethod: 'cash' },
  });
  await request(server, 'POST', `/api/admin/invoices/${inv.id}/payments`, {
    token,
    body: { amount: 30, paymentMethod: 'check' },
  });

  const history = await request(server, 'GET', `/api/admin/invoices/${inv.id}/payments`, { token });
  assert.equal(history.status, 200);
  assert.equal(history.body.payments.length, 2);
  // Payment methods should be preserved
  const methods = history.body.payments.map(p => p.paymentMethod).sort();
  assert.deepEqual(methods, ['cash', 'check']);
});

test('audit log records payment create and delete events', async () => {
  const inv = await makeInvoiceWithBalance(120);
  const payRes = await request(server, 'POST', `/api/admin/invoices/${inv.id}/payments`, {
    token,
    body: { amount: inv.total, paymentMethod: 'ach' },
  });
  const paymentId = payRes.body.payment.id;

  await request(server, 'DELETE', `/api/admin/payments/${paymentId}`, { token });

  const audit = await request(server, 'GET', `/api/admin/audit-log?recordType=payments&q=${paymentId}`, { token });
  const actions = audit.body.logs.map(l => l.action);
  assert.ok(actions.includes('create'), 'expected a create payment audit event');
  assert.ok(actions.includes('delete'), 'expected a delete payment audit event');
});
